# -*- coding: utf-8 -*-
"""gerar_testes.py)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uryoSvLeZtL7KG0AiFWjIAyax1KHACW
"""

!pip install langchain openai python-dotenv --quiet

from langchain.chat_models import AzureChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os

os.environ["AZURE_OPENAI_API_KEY"] = "SUA_CHAVE_AQUI"
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://SEU_ENDPOINT.openai.azure.com/"
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-05-15"
deployment_name = "gpt-35-turbo"

llm = AzureChatOpenAI(
    deployment_name=deployment_name,
    temperature=0.3,
    model_name="gpt-35-turbo"
)

template = """
Você é um engenheiro de software. Dada a função Python abaixo, gere testes unitários usando unittest.

Função:
{code}

Retorne apenas o código dos testes.
"""

prompt = PromptTemplate(
    input_variables=["code"],
    template=template,
)

chain = LLMChain(llm=llm, prompt=prompt)

funcao_exemplo = """
def calcular_media(lista):
    if not lista:
        return 0
    return sum(lista) / len(lista)
"""

resposta = chain.run(code=funcao_exemplo)
print("==== TESTES GERADOS ====\n")
print(resposta)

with open("test_calcular_media.py", "w") as f:
    f.write(resposta)